### ISSUE TITLE
 about display_contours

### ISSUE THREAD

**Issue by Lujun-Zhang** [Tzu-Jan/MaskRCNN_Application-on-welding-seam#2]
I can't find this function

**Comment by Tzu-Jan** [comment]
Hi,
I just checked and found out that the updated code was already lost. The only thing I have right now is just my thesis. I hope it can help you somehow. 
https://era.library.ualberta.ca/items/afc5110b-fa19-400e-bc24-1861c8b6bd36/view/b6c6f282-428f-4a32-ab38-65e32506dc40/Tung_Tzu-Jan_202112_MSc.pdf

**Comment by Tzu-Jan** [comment]
Hi,
I just checked and found out that the updated code was already lost. The only thing I have right now is just my thesis. I hope it can help you somehow.
https://era.library.ualberta.ca/items/afc5110b-fa19-400e-bc24-1861c8b6bd36/view/b6c6f282-428f-4a32-ab38-65e32506dc40/Tung_Tzu-Jan_202112_MSc.pdf
